# Generated by Django 4.0.4 on 2022-04-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_address_alter_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Student', 'Student')], max_length=20, null=True),
        ),
    ]
