# Generated by Django 4.0.4 on 2022-04-12 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_classmodel_classes_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentication.subject'),
            preserve_default=False,
        ),
    ]
