# Generated by Django 4.0.4 on 2022-04-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_student_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='classes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.classmodel'),
        ),
    ]
