# Generated by Django 4.0.4 on 2022-04-14 01:13

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_student_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.IntegerField()),
                ('otp_email', models.EmailField(max_length=254)),
                ('time_created', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(default=authentication.models.roll_number_calculator, max_length=50, unique=True),
        ),
    ]
