# Generated by Django 4.0.4 on 2022-04-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_otp_alter_student_roll_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassModel',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='classes',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='batch',
        ),
    ]
